liip_imagine:
    filter_sets:
        monsieurbiz_sylius_ui_elements_logos:
            filters:
                thumbnail: { size: [600, 600], mode: inset }
                relative_resize: { widen: 300 }
        monsieurbiz_sylius_ui_elements_text_with_image:
            filters:
                thumbnail: { size: [800, 800], mode: inset }
                relative_resize: { widen: 600 }
