services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusUiElementsPlugin\:
        resource: '../../*'
        exclude: '../../{DependencyInjection}'

